Added gulp build
ummahusla/PotatoCSS pull request #110
Opened 2017-10-12 14:02 UTC by bobharley

I have added a gulpfile that compiles and minifies sass and javascript(ES6).
The sass files are outdated so I temporarily removed the `sass` task on gulp because it will overwrite the current `potato.css` file.

And also I have created an index page for the examples. I took the html code from [potatocss.com](http://potatocss.com)

I will update and add the modal to the examples page after you merge this PR.

2017-10-12 14:05 UTC, bobharley commented on gulpfile.babel.js
> +// gulp.task('default', ['js', 'sass', 'browserSync', 'watch']);
The sass task are temporarily removed to prevent overwriting the current css.

2017-10-12 20:58 UTC, ummahusla requested changes
Merge conflicts here, sorry.

2017-10-13 00:50 UTC, bobharley commented
Fixed

2017-10-13 14:06 UTC, ummahusla approved these changes

2017-10-13 14:06 UTC, merged